In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv("../dataset/PS_20174392719_1491204439457_log.csv")

In [5]:
print("========== First 5 Rows ==========")
print(df.head())

========== First 5 Rows ==========
   step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72
2     1  TRANSFER    181.00  C1305486145          181.0            0.00
3     1  CASH_OUT    181.00   C840083671          181.0            0.00
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud
0  M1979787155             0.0             0.0        0               0
1  M2044282225             0.0             0.0        0               0
2   C553264065             0.0             0.0        1               0
3    C38997010         21182.0             0.0        1               0
4  M1230701703             0.0             0.0        0               0

In [6]:
print("\n========== Dataset Shape ==========")
print(df.shape)

========== Dataset Shape ==========
(6362620, 11)

In [7]:
print("\n========== Dataset Info ==========")
df.info()

========== Dataset Info ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

In [8]:
print("\n========== Statistical Summary ==========")
print(df.describe())

========== Statistical Summary ==========
               step        amount  oldbalanceOrg  newbalanceOrig  \
count  6.362620e+06  6.362620e+06   6.362620e+06    6.362620e+06
mean   2.433972e+02  1.798619e+05   8.338831e+05    8.551137e+05
std    1.423320e+02  6.038582e+05   2.888243e+06    2.924049e+06
min    1.000000e+00  0.000000e+00   0.000000e+00    0.000000e+00
25%    1.560000e+02  1.338957e+04   0.000000e+00    0.000000e+00
50%    2.390000e+02  7.487194e+04   1.420800e+04    0.000000e+00
75%    3.350000e+02  2.087215e+05   1.073152e+05    1.442584e+05
max    7.430000e+02  9.244552e+07   5.958504e+07    4.958504e+07

       oldbalanceDest  newbalanceDest       isFraud  isFlaggedFraud
count    6.362620e+06    6.362620e+06  6.362620e+06    6.362620e+06
mean     1.100702e+06    1.224996e+06  1.290820e-03    2.514687e-06
std      3.399180e+06    3.674129e+06  3.590480e-02    1.585775e-03
min      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00
25%      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00
50%      1.327057e+05    2.146614e+05  0.000000e+00    0.000000e+00
75%      9.430367e+05    1.111909e+06  0.000000e+00    0.000000e+00
max      3.560159e+08    3.561793e+08  1.000000e+00    1.000000e+00

In [9]:
print("\n========== Missing Values ==========")
print(df.isnull().sum())

========== Missing Values ==========
step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [10]:
print("\n========== Duplicate Rows ==========")
print(df.duplicated().sum())

========== Duplicate Rows ==========
0

In [11]:
df = df.head(100000)
df.shape

(100000, 11)

In [12]:
print("\n========== Class Distribution ==========")
print(df["isFraud"].value_counts())

print("\n========== Class Percentage ==========")
df["isFraud"].value_counts(normalize=True) * 100

========== Class Distribution ==========
isFraud
0    99884
1      116
Name: count, dtype: int64

========== Class Percentage ==========

isFraud
0    99.884
1     0.116
Name: proportion, dtype: float64

PAYMENT
TRANSFER
CASH_OUT
DEBIT
CASH_IN

In [13]:
encoder = LabelEncoder()

df["type"] = encoder.fit_transform(df["type"])
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,3,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,3,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,4,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,1,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,3,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [14]:
print("Type Encoding Mapping:")

for original, encoded in zip(
    encoder.classes_,
    encoder.transform(encoder.classes_)
):
    print(original, "->", encoded)

Type Encoding Mapping:
CASH_IN -> 0
CASH_OUT -> 1
DEBIT -> 2
PAYMENT -> 3
TRANSFER -> 4

In [16]:
import joblib
joblib.dump(encoder, "../models/type_encoder.pkl")

['../models/type_encoder.pkl']

In [17]:
import os

print(os.path.exists("../models/type_encoder.pkl"))

True

In [18]:
df = df.drop(
    columns=[
        "nameOrig",
        "nameDest"
    ]
)

In [28]:
df.head()

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,3,9839.64,170136.0,160296.36,0.0,0.0,0,0
1,1,3,1864.28,21249.0,19384.72,0.0,0.0,0,0
2,1,4,181.00,181.0,0.00,0.0,0.0,1,0
3,1,1,181.00,181.0,0.00,21182.0,0.0,1,0
4,1,3,11668.14,41554.0,29885.86,0.0,0.0,0,0

In [25]:
fraud = df[df["isFraud"] == 1].iloc[0]

print(fraud)

step                1.0
type                4.0
amount            181.0
oldbalanceOrg     181.0
newbalanceOrig      0.0
oldbalanceDest      0.0
newbalanceDest      0.0
isFraud             1.0
isFlaggedFraud      0.0
Name: 2, dtype: float64

In [21]:
X = df.drop(
    columns=[
        "isFraud"
    ]
)

y = df["isFraud"]

In [22]:
print(X.columns)

Index(['step', 'type', 'amount', 'oldbalanceOrg', 'newbalanceOrig',
       'oldbalanceDest', 'newbalanceDest', 'isFlaggedFraud'],
      dtype='object')

In [30]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [31]:
print("Training Features :", X_train.shape)
print("Testing Features :", X_test.shape)

print("Training Labels :", y_train.shape)
print("Testing Labels :", y_test.shape)

Training Features : (80000, 8)
Testing Features : (20000, 8)
Training Labels : (80000,)
Testing Labels : (20000,)

In [32]:
X_train.to_csv("../dataset/X_train.csv", index=False)
X_test.to_csv("../dataset/X_test.csv", index=False)

y_train.to_csv("../dataset/y_train.csv", index=False)
y_test.to_csv("../dataset/y_test.csv", index=False)

In [33]:
print("Preprocessing Completed Successfully!")

Preprocessing Completed Successfully!